ALTER TABLE build ADD CONSTRAINT FKBuildBranch FOREIGN KEY (branch) REFERENCES branch (id);

ALTER TABLE branch ADD CONSTRAINT FKBranchProject FOREIGN KEY (project) REFERENCES project (id);

ALTER TABLE activity ADD CONSTRAINT FkActivityTopic FOREIGN KEY (topic) REFERENCES TOPIC (id);

ALTER TABLE activity ADD CONSTRAINT FkActivityRole FOREIGN KEY (role) REFERENCES ROLE (id);

ALTER TABLE userRole ADD CONSTRAINT FkUserRoleRole FOREIGN KEY (role) REFERENCES ROLE (id);

ALTER TABLE userRole ADD CONSTRAINT FkUserRoleUser FOREIGN KEY (user) REFERENCES USER (id);

AlTER TABLE topic ADD CONSTRAINT UniqueKey UNIQUE (topicKey);